### ISSUE TITLE
errors with keras

### ISSUE THREAD

**Issue by hand-in-green** [satoshi-ikehata/CNN-PS#3]
I'm sorry for distrubing you. I run your test.py on Ubuntu16.04 with Keras2.0.3, tensorflow-gpu1.0.1 and theno0.9.0 but I'm going with two errors with keras. 
Here is the first error:

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    from keras.utils import multi_gpu_model
ImportError: cannot import name 'multi_gpu_model'

Then I comment this line but going with another error as

['/media/xy-w/Data/pycharmProgram/CNN-PS-master/DiLiGenT/pmsData/bearPNG']
load/media/xy-w/Data/pycharmProgram/CNN-PS-master/DiLiGenT/pmsData/bearPNG
...........
Traceback (most recent call last):
  File "test.py", line 50, in <module>
    main()
  File "test.py", line 44, in main
    model = load_model('weight_and_model.hdf5')
  File "/home/xy-w/software_folder/anaconda3/envs/py3.5/lib/python3.5/site-packages/keras/models.py", line 240, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/xy-w/software_folder/anaconda3/envs/py3.5/lib/python3.5/site-packages/keras/models.py", line 301, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/xy-w/software_folder/anaconda3/envs/py3.5/lib/python3.5/site-packages/keras/layers/__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "/home/xy-w/software_folder/anaconda3/envs/py3.5/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/xy-w/software_folder/anaconda3/envs/py3.5/lib/python3.5/site-packages/keras/engine/topology.py", line 2378, in from_config
    process_layer(layer_data)
  File "/home/xy-w/software_folder/anaconda3/envs/py3.5/lib/python3.5/site-packages/keras/engine/topology.py", line 2347, in process_layer
    custom_objects=custom_objects)
  File "/home/xy-w/software_folder/anaconda3/envs/py3.5/lib/python3.5/site-packages/keras/layers/__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "/home/xy-w/software_folder/anaconda3/envs/py3.5/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/xy-w/software_folder/anaconda3/envs/py3.5/lib/python3.5/site-packages/keras/layers/core.py", line 706, in from_config
    function = func_load(config['function'], globs=globs)
  File "/home/xy-w/software_folder/anaconda3/envs/py3.5/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 198, in func_load
    code = marshal.loads(code.encode('raw_unicode_escape'))
ValueError: bad marshal data (unknown type code)

So I want to known how can I fix those errors. Waiting for your answer thank you !

**Comment by satoshi-ikehata** [comment]
Thank you for the question!

>>from keras.utils import multi_gpu_model
>>ImportError: cannot import name 'multi_gpu_model'

This error simply says 'multi_gpu_model' module was not found in keras,  so I recommend you to ask about this in the keras community.

**Comment by hand-in-green** [comment]
Thank you for your replying. I updated Keras to version 2.0.9 and fix the first error. But I still cannot load your model just shown as the second error. I'm trying to find a way to handle this problem but I haven't found a suitable one yet. May I ask how can I load your model successfully? Do I need to re-create a model ?

**Comment by satoshi-ikehata** [comment]
I'm really sorry but I do not have ideas how to fix your problem (maybe some environmental issue).
The easiest way to fix this problem is to retrain the network on your machine (It will take a few hours depending on the number of iterations and the result may be slightly different from the paper). If you are interested in the training data, please send a request to sikehata@nii.ac.jp

**Comment by hand-in-green** [comment]
Still thank you for your replying I will send the request.

**Comment by yaokb8** [comment]
> 
> 
> Still thank you for your replying I will send the request.

I encountered the same error when importing the model. How did you solve it in the end?
